### ISSUE TITLE
스크롤 포지션에 따라서 상단 progress 가 보여지는 기능 추가

### ISSUE THREAD

**Issue by baramofme** [baramofme/study_log#23]
```css
.dark .progress {
    background: linear-gradient(to right, var(--subtle-yellow1) var(--scroll), transparent 0)
}
```

--scroll 변수 선언이 안됨. 아마도 변수 선언해서 넣어준 거 같다.

아래 글의 cssVars 선언하고 넣어주는 기능 사용할 것

https://www.telerik.com/blogs/passing-variables-to-css-on-a-vue-component
